// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package postgresql

import (
	"database/sql"

	"github.com/google/uuid"
)

type Deck struct {
	ID    uuid.UUID      `db:"id" json:"id"`
	Name  sql.NullString `db:"name" json:"name"`
	Owner uuid.NullUUID  `db:"owner" json:"owner"`
}

type Flashcard struct {
	ID      uuid.UUID      `db:"id" json:"id"`
	Word    sql.NullString `db:"word" json:"word"`
	Meaning sql.NullString `db:"meaning" json:"meaning"`
	Usage   []string       `db:"usage" json:"usage"`
}
