version: '3'

networks:
  languago:
    name: languago
    driver: bridge

services:
  # web:
  #   build:
  #     context: ./web
  #     target: languago-web
    
  back:
    build:
      context: ./back
      target: languago_back
    networks:
      - languago
    # depends_on:
    #   database:
    #     condition: service_healthy

  database:
    image: postgres:15
    container_name: languago_pg
    hostname: languago_db
    restart: always
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./back/cfg/schemas/postgresql/pg.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_languago:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - languago
    healthcheck:
      test: [ "CMD", "-U", "postgres", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  pg_languago: