node: 
  services:
    flashcards:
      address: "localhost"
      port: "3300"

database: 
  is_mock: true
  db_address: "localhost:5432"
  db_driver: "postgres"
  db_user: "postgres"
  db_secret: "postgres"

logger:
  logger: "logrus"
  debug: true
  env: "local"