node: 
  services:
    flashcards:
      address: "localhost"
      port: "3300"
database: 
  db_address: "localhost:5432"
  db_driver: "postgres"
  db_user: "postgres"
  db_secret: "postgres"
logger:
  logger: "zap"
  debug: true
  env: "local"