version: "0.0.1a"

node: 
  services:
    flashcards:
      address: "localhost"
      port: "3301"

database: 
  is_mock: false
  db_address: "localhost:5432"
  db_driver: "postgres"
  db_user: "languago"
  db_secret: "languago"

logger:
  logger: "logrus"
  debug: true
  env: "local"