run:
  concurrency: 6
  timeout: 20s
  issues-exit-code: 2
  # Include test files or not.
  # Default: true
  tests: false
  # List of build tags, all linters use it.
  # Default: [].
  build-tags:
  skip-dirs:
  skip-dirs-use-default: false
  skip-files:
  modules-download-mode: readonly
  allow-parallel-runners: true
  # Define the Go version limit.
  # Mainly related to generics support since go1.18.
  # Default: use Go version from the go.mod file, fallback on the env var `GOVERSION`, fallback on 1.18
  go: '1.21.1'